### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [tananaev/passport-reader#1]
Hey, it would be cool to have this app on F-Droid. Here's how to: https://f-droid.org/contribute/

**Comment by tananaev** [comment]
I believe someone has already submitted my project there.

What's the benefit of having apps there?

**Comment by pizzamaker** [comment]
Many Android users don't have Google Play, either because they are using a ROM such as Cyanogenmod or because they choose not to have nonfree programs in their phone. Additionally, anyone can install F-Droid and get libre apps, which are generally more lightweight, ad-free, gratis etc

**Comment by tananaev** [comment]
I've created a submission:

https://f-droid.org/forums/topic/e-passport-reader/

**Comment by IzzySoft** [comment]
As it still did not turn up there after almost a year now, may I suggest you publish the `.apk` here at Github? Best place would be the `releases/` page. Not too hard to do, see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help. I could then pick it up automatically and update it in [my F-Droid compatible repo](https://android.izzysoft.de/repo), which easily can be integrated with the F-Droid client.
