### ISSUE TITLE
Publish on https://f-droid.org

### ISSUE THREAD

**Issue by paulvi** [tananaev/passport-reader#11]
https://f-droid.org is alternative market for FOSS Android apps

**Comment by tananaev** [comment]
https://f-droid.org/forums/topic/e-passport-reader/

**Comment by RomainL972** [comment]
Hi, I'm trying to get the passport-reader app into F-droid. However, they asked me to use git tags to mark different versions. Would it be possible to mark different versions using tags?

**Comment by tananaev** [comment]
Do they need a full history or just last version tag?

**Comment by RomainL972** [comment]
They need a version tag for the current version, and then for the next versions to update it.

**Comment by tananaev** [comment]
Added a tag for the current version:

https://github.com/tananaev/passport-reader/tags

**Comment by RomainL972** [comment]
Thanks

**Comment by murchu27** [comment]
I installed from F-Droid, presumably this is all good now?

**Comment by RomainL972** [comment]
Yes the merge request I had created (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6583) was merged recently. I think this issue can be closed.
