### ISSUE TITLE
Option to pre-fill fields from intent and return image as base64 encoded string

### ISSUE THREAD

**Issue by peterhorsley** [tananaev/passport-reader#13]
To provide even better integration, it's handy if this app can accept values in the intent for the passport number, date of birth and expiry date, so as to pre-fill those three fields, in case the calling app already has those values (e.g. as retrieved by scanning the passport MRZ value).  This avoids the end user having to manually enter those values which leads to a better user experience.  

One further improvement for integration is to include the passport photo as a base64 encoded string in the resulting intent, which enables cordova-based apps to read the image successfully.  

Raising this issue to see if these are changes you would accept in this repo.  I have already done the code for both the above changes and can raise a PR for you to review, if so :)

Thanks!

**Comment by tananaev** [comment]
Sure, feel free to send a pull request.

**Comment by peterhorsley** [comment]
@tananaev Thanks, raised a PR for that now.

**Comment by peterhorsley** [comment]
Fixed via PR #14
