### ISSUE TITLE
Cannot read an image

### ISSUE THREAD

**Issue by viktas** [tananaev/passport-reader#29]
Hello, we’re testing your sample app and while reading a Lithuanian passport, a problem occurs, that the image cannot be read and an exception is thrown: `java.io.FileNotFoundException: /data/user/0/com.tananaev.passportreader/cache/temp.ppm (No such file or directory)`. App was tested on two devices and it is same on both. Do you have any idea how to resolve this issue? Thanks in advance.

**Comment by tananaev** [comment]
Looks like decoding failed. Do you have an ability to debug `ImageUtil` and provide original image dump?

**Comment by viktas** [comment]
I have provided it to you via email.

**Comment by tananaev** [comment]
More detailed error:
```
[WARNING]: COM marker registered as 0x0 unknown, ignoring (this might crash
           the decoder or decode a quality degraded or even useless image)
[INFO]: 1 component(s) in codestream, 1 tile(s)
        Image dimension: 480x640
[ERROR]: Specified PPM output file but compressed image is not of the correct
         format for PPM or limited decoded components to less than 3.
```

**Comment by tananaev** [comment]
Fixed by https://github.com/tananaev/passport-reader/commit/f12765f5ce98040d763d0045fc2478ed8ebc3d0c.
