### ISSUE TITLE
masterList

### ISSUE THREAD

**Issue by howardwong0208** [tananaev/passport-reader#34]
Hi, this project works well as expected.

I am just wondering where am I able to OFFICIALLY download the exact copy of masterList in the directory "app/src/main/assets/masterList" as it seems more to be more updated and contains more CSCA certs as compared to the one that is found on the official ICAO website (ICAO_ML_Jan2021.ml).

https://www.icao.int/Security/FAL/PKD/Pages/ICAO-Master-List.aspx

**Comment by RomainL972** [comment]
Hi,
You can find the exact procedure to retrieve the master list here: https://github.com/tananaev/passport-reader/pull/19#issuecomment-645885075
We use the master list provided by the government of Germany because they one from ICAO can't be used in automated workflows.

**Comment by howardwong0208** [comment]
Hi RomainL972,

Thank you very much for your explanation. Really appreciate it.
