### ISSUE TITLE
Unexpected security exception

### ISSUE THREAD

**Issue by viktasidenfy** [tananaev/passport-reader#35]
Hey, I have a problem with running my app in release mode. With `minifyEnabled true` I get an exception: 
`java.lang.IllegalStateException: Unexpected security exception during initialization`, with cause: 
`java.security.NoSuchAlgorithmException: no such algorithm: ISO9797Alg3Mac for provider BC` 
Do you know how to address this issue? Thanks in advance

**Comment by ErsinDemirbas** [comment]
Same issue did you solve this problem?

**Comment by viktasidenfy** [comment]
Add this to your proguard rules: 
`-keep class org.jmrtd.** { *; }
-keep class net.sf.scuba.** {*;}
-keep class org.bouncycastle.** {*;}
-keep class org.ejbca.** {*;}`

**Comment by ErsinDemirbas** [comment]
I solved it thanks to you. I ran into problems when I put the application in realese mode and  solved it thanks to you.
Also thanks for the quick reply, I wish you a very nice day.

Note: I'm sure this line of code will help a lot of people in the future.
