### ISSUE TITLE
Terminal Authentication

### ISSUE THREAD

**Issue by kinam06** [tananaev/passport-reader#38]
How can we do terminal authentication with the Android device? I have private key and certificate to do terminal authentication but don't know how to set parameter to doEACTA?
Anyone knows the solution please help me, thank a lot.

**Comment by RomainL972** [comment]
Hi,
Is your certificate issued by an authorized CSCA (a government) ? Otherwise, your passport won't accept your certificate and it won't work at all.

**Comment by kinam06** [comment]
Yes, I do have valid certificate and private key. I can do terminal authentication by these certificate with other ID scan devices, I just don't know how to do terminal authentication on NFC android device with jmrtd.
