### ISSUE TITLE
how to use as dep in third party app?

### ISSUE THREAD

**Issue by mvayngrib** [tananaev/passport-reader#4]
first of all, thanks for making this :)

sorry if it's a naive question, but what's the recommended way of using this in my app? Ideally I would just add a compile line to dependencies in my build.gradle

**Comment by tananaev** [comment]
If you want to compile it into your app, you should just copy the source code.

**Comment by mvayngrib** [comment]
@tananaev ic, so you don't want to publish this as a library?

**Comment by tananaev** [comment]
It is not a library at the moment. If you want to extract some code into a library, feel free to send a pull request. Unfortunately I don't have time to do it myself.

**Comment by mvayngrib** [comment]
@tananaev understood, thanks
