### ISSUE TITLE
Bump to new release

### ISSUE THREAD

**Issue by RomainL972** [tananaev/passport-reader#42]
Hi,

Since there has been some commits since the latest tag, is it possible to create a new tag and bump the Android version code so F-Droid can build a new version of the app with all the latest changes ?

Best regards,

Romain Lebbadi-Breteau

**Comment by tananaev** [comment]
We will tag with next release. Commits were just to fix CI issues.

**Comment by RomainL972** [comment]
I was wondering when do you plan to publish a new release ? Even if it's not much, the latest version of the source code uses a more recent version of Android and NDK, there have been a lot of masterList updates and there also was a fix for Passive Authentication with some passports.
