### ISSUE TITLE
No "done" button after personal info entry

### ISSUE THREAD

**Issue by jidanni** [tananaev/passport-reader#48]
Cannot find the "done" button on the bottom of the details entry page. So cannot proceed to the next step.
Yes, I tried horizontal and vertical modes.
We enter a passport number, date of expiration, and date of birth, but there is no done button to finish. I don't have my screen magnification that high that it might have shoved it off I hope. Android 12.

**Comment by tananaev** [comment]
You don't need a done button. Once you enter the details you can start scanning.

**Comment by jidanni** [comment]
Well, what probably happened was, I added  little too many numbers for my passport number, and it probably scanned it several times, and that caused my passport to lock up forever. Who knows?

That is why it is very important to have a done button, to ensure the user has correctly entered all his information, before scanning starts. Else he could certainly very easily lock up his passport due to several attempts using the wrong information!

**Comment by tananaev** [comment]
I don't think a passport can get locked.
