### ISSUE TITLE
Where does the masterlist file come from?

### ISSUE THREAD

**Issue by panicg** [tananaev/passport-reader#52]
hello.

Thanks to you, we are implementing the electronic passport reading function.

I would like to know the source of Masterlist.

According to what I found, it is a .ml file that is updated every 3 months on the ICAO homepage. Are you converting and updating based on this file?

If so, can you explain how to convert it?

**Comment by tananaev** [comment]
https://github.com/tananaev/passport-reader/blob/master/.github/workflows/main.yml
