### ISSUE TITLE
Why we don't use verifyAA in this project

### ISSUE THREAD

**Issue by sontranit1996** [tananaev/passport-reader#61]
Dear Dev,
Can you explain for me why we don't use verifyAA in this project. My app need AAChallenge and AASignature and I can't take it.
Thank you
![Uploading 122.PNG…]()

**Comment by tananaev** [comment]
No, unfortunately not.

**Comment by sontranit1996** [comment]
Why don't we need to do that anymore? I found this function in legacy/passport :(

**Comment by tananaev** [comment]
Link?

**Comment by sontranit1996** [comment]
[](https://github.com/tananaev/passport-reader/blob/master/legacy/Passport.java)
Line 910 to 1067

**Comment by sontranit1996** [comment]
https://github.com/tananaev/passport-reader/blob/master/legacy/Passport.java

**Comment by sontranit1996** [comment]
Or there is a new function to do that. **"Active Authentication"**

**Comment by tananaev** [comment]
That code is not ours.
